export interface Student {
  registrationNumber: string;
  studentNumber: string;
  firstName: string;
  lastName: string;
  gender: 'Male' | 'Female';
  email: string;
  password: string;
}

export const studentData: Student[] = [
  {
    registrationNumber: '24/U/BEL/02018/PD',
    studentNumber: '2400802018',
    firstName: 'Immaculate',
    lastName: 'Ssebaduka',
    gender: 'Female',
    email: 'ssebadukaimmaculate@gmail.com',
    password: 'Immaculate',
  },
  {
    registrationNumber: '24/U/BET/02116/PE',
    studentNumber: '2400802116',
    firstName: 'Scovia',
    lastName: 'Nabirye',
    gender: 'Female',
    email: 'nabiryescovia@gmail.com',
    password: 'Scovia',
  },
  {
    registrationNumber: '24/U/BEL/002/GV',
    studentNumber: '2400800002',
    firstName: 'Emmanuel',
    lastName: 'Odongo',
    gender: 'Male',
    email: 'emmanuelodongo@gmail.com',
    password: 'Emmanuel',
  },
  {
    registrationNumber: '24/U/BET/18794/PE',
    studentNumber: '2400818794',
    firstName: 'Immaculate',
    lastName: 'Ssebaggala',
    gender: 'Female',
    email: 'ssebaggalaimmaculate@gmail.com',
    password: 'Immaculate',
  },
  {
    registrationNumber: '24/U/BET/02544/PE',
    studentNumber: '2400802544',
    firstName: 'Francis',
    lastName: 'Nansubuga',
    gender: 'Male',
    email: 'francisnansubuga@gmail.com',
    password: 'Francis',
  },
  {
    registrationNumber: '24/U/BEL/019/GV',
    studentNumber: '2400800019',
    firstName: 'James',
    lastName: 'Nansubuga',
    gender: 'Male',
    email: 'jamesnansubuga@gmail.com',
    password: 'James',
  },
  {
    registrationNumber: '24/U/BEL/0852/PD',
    studentNumber: '2400800852',
    firstName: 'Agnes',
    lastName: 'Okello',
    gender: 'Female',
    email: 'okelloagnes@gmail.com',
    password: 'Agnes',
  },
  {
    registrationNumber: '24/U/BEL/04446/PD',
    studentNumber: '2400804446',
    firstName: 'Andrew',
    lastName: 'Ssemwogerere',
    gender: 'Male',
    email: 'andrewssemwogerere@gmail.com',
    password: 'Andrew',
  },
  {
    registrationNumber: '24/U/BEL/18845/PD',
    studentNumber: '2400818845',
    firstName: 'Peter',
    lastName: 'Nabirye',
    gender: 'Male',
    email: 'peternabirye@gmail.com',
    password: 'Peter',
  },
  {
    registrationNumber: '24/U/BEL/0958/PD',
    studentNumber: '2400800958',
    firstName: 'Stella',
    lastName: 'Nalubwama',
    gender: 'Female',
    email: 'nalubwamastella@gmail.com',
    password: 'Stella',
  },
  {
    registrationNumber: '24/U/BEL/18852/PD',
    studentNumber: '2400818852',
    firstName: 'Sarah',
    lastName: 'Kato',
    gender: 'Female',
    email: 'katosarah@gmail.com',
    password: 'Sarah',
  },
  {
    registrationNumber: '24/U/BEL/103/GV',
    studentNumber: '2400800103',
    firstName: 'Prossy',
    lastName: 'Ssemanda',
    gender: 'Female',
    email: 'ssemandaprossy@gmail.com',
    password: 'Prossy',
  },
  {
    registrationNumber: '24/U/BEL/18898/PD',
    studentNumber: '2400818898',
    firstName: 'Kenneth',
    lastName: 'Ochieng',
    gender: 'Male',
    email: 'kennethochieng@gmail.com',
    password: 'Kenneth',
  },
  {
    registrationNumber: '24/U/BEL/126/GV',
    studentNumber: '2400800126',
    firstName: 'Dorcas',
    lastName: 'Nalubwama',
    gender: 'Female',
    email: 'nalubwamadorcas@gmail.com',
    password: 'Dorcas',
  },
  {
    registrationNumber: '24/U/BET/05788/PE',
    studentNumber: '2400805788',
    firstName: 'Annet',
    lastName: 'Ssebaduka',
    gender: 'Female',
    email: 'ssebadukaannet@gmail.com',
    password: 'Annet',
  },
  {
    registrationNumber: '24/U/BET/06044/PE',
    studentNumber: '2400806044',
    firstName: 'Joseph',
    lastName: 'Nabirye',
    gender: 'Male',
    email: 'josephnabirye@gmail.com',
    password: 'Joseph',
  },
  {
    registrationNumber: '24/U/BEL/06345/PD',
    studentNumber: '2400806345',
    firstName: 'Geoffrey',
    lastName: 'Namugga',
    gender: 'Male',
    email: 'geoffreynamugga@gmail.com',
    password: 'Geoffrey',
  },
  {
    registrationNumber: '24/U/BEL/17216/GV',
    studentNumber: '2400817216',
    firstName: 'Brenda',
    lastName: 'Nakibuuka',
    gender: 'Female',
    email: 'nakibuukabrenda@gmail.com',
    password: 'Brenda',
  },
  {
    registrationNumber: '24/U/BET/18925/PE',
    studentNumber: '2400818925',
    firstName: 'Brian',
    lastName: 'Nabirye',
    gender: 'Male',
    email: 'briannabirye@gmail.com',
    password: 'Brian',
  },
  {
    registrationNumber: '24/U/BEL/06758/PD',
    studentNumber: '2400806758',
    firstName: 'Martin',
    lastName: 'Nalumu',
    gender: 'Male',
    email: 'martinnalumu@gmail.com',
    password: 'Martin',
  },
  {
    registrationNumber: '21/U/BEL/16115/GV',
    studentNumber: '2100816115',
    firstName: 'Patrick',
    lastName: 'Ssebulime',
    gender: 'Male',
    email: 'patrickssebulime@gmail.com',
    password: 'Patrick',
  },
  {
    registrationNumber: '24/U/BET/07090/PE',
    studentNumber: '2400807090',
    firstName: 'Joseph',
    lastName: 'Ssebaggala',
    gender: 'Male',
    email: 'josephssebaggala@gmail.com',
    password: 'Joseph',
  },
  {
    registrationNumber: '24/U/BEL/18958/PD',
    studentNumber: '2400818958',
    firstName: 'Grace',
    lastName: 'Nambi',
    gender: 'Female',
    email: 'nambigrace@gmail.com',
    password: 'Grace',
  },
  {
    registrationNumber: '24/U/BET/07313/PE',
    studentNumber: '2400807313',
    firstName: 'Sharon',
    lastName: 'Kato',
    gender: 'Female',
    email: 'katosharon@gmail.com',
    password: 'Sharon',
  },
  {
    registrationNumber: '24/U/BET/18972/PE',
    studentNumber: '2400818972',
    firstName: 'Grace',
    lastName: 'Nalubwama',
    gender: 'Female',
    email: 'nalubwamagrace@gmail.com',
    password: 'Grace',
  },
  {
    registrationNumber: '24/U/BET/1296/PE',
    studentNumber: '2400801296',
    firstName: 'Charles',
    lastName: 'Namuddu',
    gender: 'Male',
    email: 'charlesnamuddu@gmail.com',
    password: 'Charles',
  },
  {
    registrationNumber: '24/U/BEL/211/GV',
    studentNumber: '2400800211',
    firstName: 'Esther',
    lastName: 'Nalweyiso',
    gender: 'Female',
    email: 'nalweyisoesther@gmail.com',
    password: 'Esther',
  },
  {
    registrationNumber: '24/U/BET/07859/PE',
    studentNumber: '2400807859',
    firstName: 'Martin',
    lastName: 'Nakato',
    gender: 'Male',
    email: 'martinnakato@gmail.com',
    password: 'Martin',
  },
  {
    registrationNumber: '24/U/BET/19006/PE',
    studentNumber: '2400819006',
    firstName: 'John',
    lastName: 'Nalwoga',
    gender: 'Male',
    email: 'johnnalwoga@gmail.com',
    password: 'John',
  },
  {
    registrationNumber: '24/U/BET/19009/PE',
    studentNumber: '2400819009',
    firstName: 'Brenda',
    lastName: 'Nalubowa',
    gender: 'Female',
    email: 'nalubowabrenda@gmail.com',
    password: 'Brenda',
  },
  {
    registrationNumber: '24/U/BEL/1382/PD',
    studentNumber: '2400801382',
    firstName: 'Patrick',
    lastName: 'Ochieng',
    gender: 'Male',
    email: 'patrickochieng@gmail.com',
    password: 'Patrick',
  },
  {
    registrationNumber: '24/U/BET/19021/PE',
    studentNumber: '2400819021',
    firstName: 'Joyce',
    lastName: 'Nalule',
    gender: 'Female',
    email: 'nalulejoyce@gmail.com',
    password: 'Joyce',
  },
  {
    registrationNumber: '24/U/BEL/09942/PD',
    studentNumber: '2400809942',
    firstName: 'David',
    lastName: 'Ochieng',
    gender: 'Male',
    email: 'davidochieng@gmail.com',
    password: 'David',
  },
  {
    registrationNumber: '24/U/BET/1521/PE',
    studentNumber: '2400801521',
    firstName: 'Esther',
    lastName: 'Nakato',
    gender: 'Female',
    email: 'nakatoesther@gmail.com',
    password: 'Esther',
  },
  {
    registrationNumber: '24/U/BET/1580/PE',
    studentNumber: '2400801580',
    firstName: 'Judith',
    lastName: 'Ssenyonjo',
    gender: 'Female',
    email: 'ssenyonjojudith@gmail.com',
    password: 'Judith',
  },
  {
    registrationNumber: '24/U/BEL/10662/PD',
    studentNumber: '2400810662',
    firstName: 'Stephen',
    lastName: 'Nabirye',
    gender: 'Male',
    email: 'stephennabirye@gmail.com',
    password: 'Stephen',
  },
  {
    registrationNumber: '24/U/BEL/1596/PD',
    studentNumber: '2400801596',
    firstName: 'Judith',
    lastName: 'Kato',
    gender: 'Female',
    email: 'katojudith@gmail.com',
    password: 'Judith',
  },
  {
    registrationNumber: '24/U/BET/1603/PE',
    studentNumber: '2400801603',
    firstName: 'Simon',
    lastName: 'Ssekandi',
    gender: 'Male',
    email: 'simonssekandi@gmail.com',
    password: 'Simon',
  },
  {
    registrationNumber: '24/U/BEL/19060/PD',
    studentNumber: '2400819060',
    firstName: 'Phillip',
    lastName: 'Ssemanda',
    gender: 'Male',
    email: 'phillipssemanda@gmail.com',
    password: 'Phillip',
  },
  {
    registrationNumber: '24/U/BET/19062/PE',
    studentNumber: '2400819062',
    firstName: 'Gloria',
    lastName: 'Nakato',
    gender: 'Female',
    email: 'nakatogloria@gmail.com',
    password: 'Gloria',
  },
  {
    registrationNumber: '24/U/BET/1635/PE',
    studentNumber: '2400801635',
    firstName: 'Patrick',
    lastName: 'Ssekitoleko',
    gender: 'Male',
    email: 'patrickssekitoleko@gmail.com',
    password: 'Patrick',
  },
  {
    registrationNumber: '24/U/BET/19072/PE',
    studentNumber: '2400819072',
    firstName: 'Esther',
    lastName: 'Nakato',
    gender: 'Female',
    email: 'nakatoesther@gmail.com',
    password: 'Esther',
  },
  {
    registrationNumber: '24/X/BEL/10978/PD',
    studentNumber: '2400810978',
    firstName: 'George',
    lastName: 'Kato',
    gender: 'Male',
    email: 'georgekato@gmail.com',
    password: 'George',
  },
  {
    registrationNumber: '24/U/BET/19076/PE',
    studentNumber: '2400819076',
    firstName: 'Immaculate',
    lastName: 'Nambi',
    gender: 'Female',
    email: 'nambiimmaculate@gmail.com',
    password: 'Immaculate',
  },
  {
    registrationNumber: '24/U/BET/19079/PE',
    studentNumber: '2400819079',
    firstName: 'Emmanuel',
    lastName: 'Muwonge',
    gender: 'Male',
    email: 'emmanuelmuwonge@gmail.com',
    password: 'Emmanuel',
  },
  {
    registrationNumber: '24/U/BET/11106/PE',
    studentNumber: '2400811106',
    firstName: 'Christine',
    lastName: 'Ssebaduka',
    gender: 'Female',
    email: 'ssebadukachristine@gmail.com',
    password: 'Christine',
  },
  {
    registrationNumber: '24/U/BEL/19091/PD',
    studentNumber: '2400819091',
    firstName: 'Agnes',
    lastName: 'Ssekitoleko',
    gender: 'Female',
    email: 'ssekitolekoagnes@gmail.com',
    password: 'Agnes',
  },
  {
    registrationNumber: '24/U/BEL/323/GV',
    studentNumber: '2400800323',
    firstName: 'Grace',
    lastName: 'Okello',
    gender: 'Female',
    email: 'okellograce@gmail.com',
    password: 'Grace',
  },
  {
    registrationNumber: '24/U/BEL/324/GV',
    studentNumber: '2400800324',
    firstName: 'Andrew',
    lastName: 'Nalwoga',
    gender: 'Male',
    email: 'andrewnalwoga@gmail.com',
    password: 'Andrew',
  },
  {
    registrationNumber: '24/U/BET/11507/PE',
    studentNumber: '2400811507',
    firstName: 'Harriet',
    lastName: 'Nakato',
    gender: 'Female',
    email: 'nakatoharriet@gmail.com',
    password: 'Harriet',
  },
  {
    registrationNumber: '24/U/BEL/1757/PD',
    studentNumber: '2400801757',
    firstName: 'Patrick',
    lastName: 'Nalubwama',
    gender: 'Male',
    email: 'patricknalubwama@gmail.com',
    password: 'Patrick',
  },
  {
    registrationNumber: '24/U/BET/11640/PE',
    studentNumber: '2400811640',
    firstName: 'Kenneth',
    lastName: 'Ssekitoleko',
    gender: 'Male',
    email: 'kennethssekitoleko@gmail.com',
    password: 'Kenneth',
  },
  {
    registrationNumber: '24/U/BET/11662/PE',
    studentNumber: '2400811662',
    firstName: 'Vincent',
    lastName: 'Nansubuga',
    gender: 'Male',
    email: 'vincentnansubuga@gmail.com',
    password: 'Vincent',
  },
  {
    registrationNumber: '24/U/BEL/11810/PD',
    studentNumber: '2400811810',
    firstName: 'Agnes',
    lastName: 'Ochieng',
    gender: 'Female',
    email: 'ochiengagnes@gmail.com',
    password: 'Agnes',
  },
  {
    registrationNumber: '24/U/BET/11867/PE',
    studentNumber: '2400811867',
    firstName: 'Florence',
    lastName: 'Ssemwogerere',
    gender: 'Female',
    email: 'ssemwogerereflorence@gmail.com',
    password: 'Florence',
  },
  {
    registrationNumber: '24/U/BET/1790/PE',
    studentNumber: '2400801790',
    firstName: 'Sylvia',
    lastName: 'Ssemanda',
    gender: 'Female',
    email: 'ssemandasylvia@gmail.com',
    password: 'Sylvia',
  },
  {
    registrationNumber: '24/U/BEL/1804/PD',
    studentNumber: '2400801804',
    firstName: 'Jennifer',
    lastName: 'Nalwoga',
    gender: 'Female',
    email: 'nalwogajennifer@gmail.com',
    password: 'Jennifer',
  },
  {
    registrationNumber: '24/U/BET/12200/PE',
    studentNumber: '2400812200',
    firstName: 'Norah',
    lastName: 'Ssekitto',
    gender: 'Female',
    email: 'ssekittonorah@gmail.com',
    password: 'Norah',
  },
  {
    registrationNumber: '24/U/BEL/368/GV',
    studentNumber: '2400800368',
    firstName: 'Thomas',
    lastName: 'Ssemwogerere',
    gender: 'Male',
    email: 'thomasssemwogerere@gmail.com',
    password: 'Thomas',
  },
  {
    registrationNumber: '24/U/BEL/12598/PD',
    studentNumber: '2400812598',
    firstName: 'Geoffrey',
    lastName: 'Kato',
    gender: 'Male',
    email: 'geoffreykato@gmail.com',
    password: 'Geoffrey',
  },
  {
    registrationNumber: '24/U/BET/1886/PE',
    studentNumber: '2400801886',
    firstName: 'Michael',
    lastName: 'Ssemanda',
    gender: 'Male',
    email: 'michaelssemanda@gmail.com',
    password: 'Michael',
  },
];